backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow
site_url: https://salah-board.netlify.app

media_folder: "assets/images" # Media files will be stored in the repo under cms/images
public_folder: "/img" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "timings"
    label: "timings"
    folder: "content/timings"
    format: 'frontmatter'
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
  
  - name: "ads"
    folder: "content/ads"
    label: "ads"
    create: true
    format: 'frontmatter'
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}